"""CH-14a step 1a - measure the submission size HONESTLY, before touching anything.

`QUESTIONS.md` Q25 raised the tracked tree at 59.4 MB against HackerEarth's 50 MB cap
and called it a submission blocker. This script is the before-picture. It measures
BOTH quantities, because Q25's own diagnosis - "a guard that measures a proxy and
reports ok while the real limit is breached" - cuts both ways:

    (a) total TRACKED BYTES, uncompressed. What Q25 measured.
    (b) the size of `git archive --format=zip HEAD`. What is actually UPLOADED,
        and therefore the only quantity the 50 MB cap in `QUESTIONS.md` Q2 (C1)
        constrains: "Source Code - an UPLOADED FILE (zip). MAX 50 MB."

Pure: no network, no clock, no randomness. Reads git plumbing and the filesystem.

    python docs/evidence/ch14-size/inventory.py > docs/evidence/ch14-size/inventory.md
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import zipfile
from collections import Counter
from pathlib import Path

THRESHOLD = 256 * 1024          # the prompt's reporting floor
CAP_BYTES = 50_000_000          # HackerEarth, QUESTIONS.md Q2 C1
TARGET_BYTES = 45_000_000       # CH-14a's headroom target


def sh(*args: str) -> str:
    return subprocess.run(args, capture_output=True, text=True, check=True).stdout


def main() -> int:
    repo = Path(sh("git", "rev-parse", "--show-toplevel").strip())
    os.chdir(repo)

    head = sh("git", "rev-parse", "HEAD").strip()
    tracked = [p for p in sh("git", "ls-files", "-z").split("\0") if p]

    sizes: list[tuple[int, str]] = []
    missing: list[str] = []
    for p in tracked:
        try:
            sizes.append((os.path.getsize(p), p))
        except OSError:
            missing.append(p)
    sizes.sort(reverse=True)
    total = sum(s for s, _ in sizes)

    # --- the archive, built exactly as the submission would be -----------------
    with tempfile.TemporaryDirectory() as td:
        zpath = Path(td) / "submission.zip"
        subprocess.run(["git", "archive", "--format=zip", "-o", str(zpath), "HEAD"],
                       check=True, capture_output=True)
        zip_bytes = zpath.stat().st_size
        with zipfile.ZipFile(zpath) as z:
            infos = z.infolist()
            entries = len(infos)
            raw_in_zip = sum(i.file_size for i in infos)
            cmp_in_zip = sum(i.compress_size for i in infos)
            worst = sorted(infos, key=lambda i: -i.compress_size)[:15]
            worst_rows = [(i.compress_size, i.file_size, i.filename) for i in worst]

    by_area: Counter[str] = Counter()
    count_area: Counter[str] = Counter()
    for s, p in sizes:
        area = "/".join(p.split("/")[:2]) if "/" in p else "(repo root)"
        by_area[area] += s
        count_area[area] += 1

    out = sys.stdout.write
    out("# CH-14a - submission size inventory (the before-picture)\n\n")
    out("Generated by `docs/evidence/ch14-size/inventory.py`. No network, no clock, "
        "no randomness.\n\n")
    out(f"- commit measured : `{head}`\n")
    out(f"- tracked files   : **{len(tracked)}**"
        f"{'' if not missing else f' ({len(missing)} tracked but absent on disk)'}\n")
    out(f"- tracked bytes   : **{total:,} B = {total/1e6:.2f} MB "
        f"= {total/1024/1024:.2f} MiB**\n")
    out(f"- `git archive --format=zip HEAD` : **{zip_bytes:,} B = "
        f"{zip_bytes/1e6:.2f} MB = {zip_bytes/1024/1024:.2f} MiB**\n")
    out(f"- HackerEarth cap : {CAP_BYTES:,} B = {CAP_BYTES/1e6:.0f} MB "
        "(`QUESTIONS.md` Q2, C1 - the cap is on the UPLOADED FILE)\n\n")

    verdict = "UNDER" if zip_bytes < CAP_BYTES else "OVER"
    head_room = CAP_BYTES - zip_bytes
    out(f"**The uploaded artifact is {verdict} the cap by "
        f"{abs(head_room):,} B ({abs(head_room)/1e6:.2f} MB), a factor of "
        f"{CAP_BYTES/zip_bytes:.2f}x.**\n\n")
    out(f"The tracked tree is {'over' if total > CAP_BYTES else 'under'} "
        f"the cap by {abs(CAP_BYTES-total)/1e6:.2f} MB, but the tracked tree is not "
        "what is uploaded. The zip is.\n\n")
    out(f"Compression across the whole archive: {raw_in_zip:,} B raw -> "
        f"{cmp_in_zip:,} B compressed = **{raw_in_zip/cmp_in_zip:.2f}x**, over "
        f"{entries} zip entries ({len(tracked)} files + directory records).\n\n")

    out("## Every tracked path at or over 256 KB\n\n")
    out("| bytes | MB | path |\n|---:|---:|---|\n")
    n_over = 0
    for s, p in sizes:
        if s >= THRESHOLD:
            n_over += 1
            out(f"| {s:,} | {s/1e6:.3f} | `{p}` |\n")
    over_total = sum(s for s, _ in sizes if s >= THRESHOLD)
    out(f"\n{n_over} paths at or over 256 KB, {over_total:,} B "
        f"({over_total/1e6:.2f} MB) = {100*over_total/total:.1f}% of the tracked tree.\n\n")

    out("## Tracked bytes by area\n\n")
    out("| area | MB | files |\n|---|---:|---:|\n")
    for area, b in by_area.most_common():
        if b >= 100_000:
            out(f"| `{area}` | {b/1e6:.3f} | {count_area[area]} |\n")
    tail = sum(b for a, b in by_area.items() if b < 100_000)
    tail_n = sum(count_area[a] for a, b in by_area.items() if b < 100_000)
    out(f"| *(everything under 0.1 MB)* | {tail/1e6:.3f} | {tail_n} |\n")
    out(f"| **TOTAL** | **{total/1e6:.3f}** | **{len(tracked)}** |\n\n")

    out("## The same files, measured as the judge receives them\n\n")
    out("Largest COMPRESSED contributors to the upload. The ordering is not the "
        "ordering of the raw table above, and that difference is the finding.\n\n")
    out("| compressed B | raw B | ratio | path |\n|---:|---:|---:|---|\n")
    for c, r, name in worst_rows:
        out(f"| {c:,} | {r:,} | {r/max(c,1):.1f}x | `{name}` |\n")
    out("\n")

    out("## What this measurement changes\n\n")
    out("The two largest files in the tracked tree - `data/attribution-v11/"
        "amdpars_v11.jsonl` and `data/amdpars/amdpars.jsonl`, 15.02 MB together and "
        "named as the top of the blocker - contribute "
        f"{sum(c for c,_,n in worst_rows if n.endswith(('amdpars_v11.jsonl','amdpars/amdpars.jsonl')))/1e6:.2f} MB "
        "to the upload between them. They are line-oriented JSON with a repeating key "
        "set and they deflate about 21x.\n\n")
    out("Raw size was the proxy. Archive size is the constraint. "
        "`QUESTIONS.md` Q27 records the consequence.\n")

    if missing:
        out("\n## Tracked but absent on disk\n\n")
        for p in missing:
            out(f"- `{p}`\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
